services:
  db:
    container_name: pgsql
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - volume_database:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  volume_database:

networks:
  dev:
